export const enum CalendarDataTeatId {
    MODAL_NO_REVIEW = 'modal-no-review',
    MODAL_ERROR_USER_TRAINING_TITLE = 'modal-error-user-training-title',
    MODAL_ERROR_USER_TRAINING_SUBTITLE = 'modal-error-user-training-subtitle',
    MODAL_ERROR_USER_TRAINING_BUTTON = 'modal-error-user-training-button',
    MODAL_ERROR_USER_TRAINING_BUTTON_CLOSE = 'modal-error-user-training-button-close',
    MENU_BUTTON_CALENDAR = 'menu-button-calendar',
    MODAL_CREATE_TRAINING = 'modal-create-training',
    MODAL_CREATE_TRAINING_BUTTON_CLOSE = 'modal-create-training-button-close',
    MODAL_UPDATE_TRAINING_EDIT_BUTTON_INDEX = 'modal-update-training-edit-button',
    MODAL_CREATE_EXERCISE = 'modal-create-exercise',
    MODAL_CREATE_EXERCISE_SELECT = 'modal-create-exercise-select',
    MODAL_EXERCISE_TRAINING_BUTTON_CLOSE = 'modal-exercise-training-button-close',
    MODAL_DRAWER_RIGHT = 'modal-drawer-right',
    MODAL_DRAWER_RIGHT_BUTTON_CLOSE = 'modal-drawer-right-button-close',
    MODAL_DRAWER_RIGHT_INPUT_EXERCISE_INDEX = 'modal-drawer-right-input-exercise',
    MODAL_DRAWER_RIGHT_CHECKBOX_EXERCISE_INDEX = 'modal-drawer-right-checkbox-exercise',
    MODAL_DRAWER_RIGHT_INPUT_APPROACH_INDEX = 'modal-drawer-right-input-approach',
    MODAL_DRAWER_RIGHT_INPUT_WEIGHT_INDEX = 'modal-drawer-right-input-weight',
    MODAL_DRAWER_RIGHT_INPUT_QUANTITY_INDEX = 'modal-drawer-right-input-quantity',
}

export const enum ProfileDataTestId {
    MENU_BUTTON_PRIFILE = 'menu-button-profile',
    HEADER_SETTINGS = 'header-settings',
    INPUT_PROFILE_NAME = 'profile-name',
    INPUT_PROFILE_SURNAME = 'profile-surname',
    PROFILE_AVATAR = 'profile-avatar',
    INPUT_PROFILE_EMAIL = 'profile-email',
    PROFILE_BIRTHDAY = 'profile-birthday',
    PROFILE_PASSWORD = 'profile-password',
    PROFILE_REPEAT_PASSWORD = 'profile-repeat-password',
    PROFILE_SUBMIT = 'profile-submit',
    BIG_FILE_ERROR_CLOSE = 'big-file-error-close',
    ALERT = 'alert',
    SETTINGS_BACK = 'settings-back',
    PRO_TARIFF_CARD = 'pro-tariff-card',
    ACTIVATE_TARIFF_BTN = 'activate-tariff-btn',
    SWITCH_TARIFF_TRAININGS = 'tariff-trainings',
    SWITCH_TARIFF_NOTIFICATION = 'tariff-notifications',
    SWITCH_TARIFF_THEME = 'tariff-theme',
    TARIFF_TRAINING_ICON = 'tariff-trainings-icon',
    TARIFF_NOTIFICATIONS_ICON = 'tariff-notifications-icon',
    TARIFF_THEME_ICON = 'tariff-theme-icon',
    TARIFF_SIDER = 'tariff-sider',
    TARIFF_COST = 'tariff-cost',
    TARIFF_MODAL_SUCCESS = 'tariff-modal-success',
    TARIFF_SUBMIT = 'tariff-submit',
    NEW_REVIEW_SUBMIT_BUTTON = 'new-review-submit-button',
    TARIFF_10 = 'tariff-10',
}

export const enum TrainingDataTestId {
    MY_TRAININGS_TABLE = 'my-trainings-table',
    CREATE_NEW_TRAINING_BUTTON = 'create-new-training-button',
    UPDATE_MY_TRAINING_TABLE_ICON_INDEX = 'update-my-training-table-icon',
    CREATE_TRAINING_SUCCESS_ALERT = 'create-training-success-alert',
    NOTIFICATION_ABOUT_JOINT_TRAINING = 'notification-about-joint-training',
    JOINT_TRAINING_CARDS_INDEX = 'joint-training-cards',
    JOINT_TRAINING_REVIEW_CARD = 'joint-training-review-card',
    MODAL_DRAWER_RIGHT_DATE_PICKER = 'modal-drawer-right-date-picker',
    MODAL_DRAWER_RIGHT_CHECKBOX_PERIOD = 'modal-drawer-right-checkbox-period',
    MODAL_DRAWER_RIGHT_SELECT_PERIOD = 'modal-drawer-right-select-period',
    SEARCH_INPUT = 'search-input',
    PARTNER_MODAL = 'partner-modal',
    MENU_BUTTON_TRAINING = 'menu-button-training',
}

export const enum AchievementDataTestId {
    SIDEBAR_ACHIEVEMENTS = 'sidebar-achievements',
}
