export const enum CalendarDataTeatId {
    MODAL_NO_REVIEW = 'modal-no-review',
    MODAL_ERROR_USER_TRAINING_TITLE = 'modal-error-user-training-title',
    MODAL_ERROR_USER_TRAINING_SUBTITLE = 'modal-error-user-training-subtitle',
    MODAL_ERROR_USER_TRAINING_BUTTON = 'modal-error-user-training-button',
    MODAL_ERROR_USER_TRAINING_BUTTON_CLOSE = 'modal-error-user-training-button-close',
    MENU_BUTTON_CALENDAR = 'menu-button-calendar',
    MODAL_CREATE_TRAINING = 'modal-create-training',
    MODAL_CREATE_TRAINING_BUTTON_CLOSE = 'modal-create-training-button-close',
    MODAL_UPDATE_TRAINING_EDIT_BUTTON_INDEX = 'modal-update-training-edit-button',
    MODAL_CREATE_EXERCISE = 'modal-create-exercise',
    MODAL_CREATE_EXERCISE_SELECT = 'modal-create-exercise-select',
    MODAL_EXERCISE_TRAINING_BUTTON_CLOSE = 'modal-exercise-training-button-close',
    MODAL_DRAWER_RIGHT = 'modal-drawer-right',
    MODAL_DRAWER_RIGHT_BUTTON_CLOSE = 'modal-drawer-right-button-close',
    MODAL_DRAWER_RIGHT_INPUT_EXERCISE_INDEX = 'modal-drawer-right-input-exercise',
    MODAL_DRAWER_RIGHT_CHECKBOX_EXERCISE_INDEX = 'modal-drawer-right-checkbox-exercise',
    MODAL_DRAWER_RIGHT_INPUT_APPROACH_INDEX = 'modal-drawer-right-input-approach',
    MODAL_DRAWER_RIGHT_INPUT_WEIGHT_INDEX = 'modal-drawer-right-input-weight',
    MODAL_DRAWER_RIGHT_INPUT_QUANTITY_INDEX = 'modal-drawer-right-input-quantity',
}
